In [24]:
import backend

Game = backend.GameManager("2022-06-06", "BTC/USD")
Data_df = Game.get_stock_prices("BTC/USD", f"2022-08-09 00:00", f"2022-08-10 01:00") 
lastpos = Data_df.loc[len(Data_df)-1, "close"]
sData_df = Data_df.iloc[9::10, :].reset_index(drop=True)
Data_df = Data_df.iloc[::10, :].reset_index(drop=True)


Data_df["close"] = sData_df["close"]
Data_df.loc[len(Data_df)-1,"close"] = lastpos
Data_df

                          date          open  ...           low         close
0    2022-08-09 00:00:00+00:00  23830.109375  ...  23814.039062  23800.269531
1    2022-08-09 00:10:00+00:00  23803.330078  ...  23796.339844  23811.070312
2    2022-08-09 00:20:00+00:00  23809.599609  ...  23809.599609  23826.619141
3    2022-08-09 00:30:00+00:00  23825.990234  ...  23816.740234  23851.529297
4    2022-08-09 00:40:00+00:00  23855.109375  ...  23834.710938  23823.810547
..                         ...           ...  ...           ...           ...
146  2022-08-10 00:20:00+00:00  23050.220703  ...  23050.220703  23048.419922
147  2022-08-10 00:30:00+00:00  23046.429688  ...  23036.369141  22922.750000
148  2022-08-10 00:40:00+00:00  22913.640625  ...  22898.439453  22729.380859
149  2022-08-10 00:50:00+00:00  22731.750000  ...  22729.380859  22766.449219
150  2022-08-10 01:00:00+00:00  22778.599609  ...  22766.449219  22787.300781

[151 rows x 5 columns]

In [11]:
import backend

Game = backend.GameManager("2022-06-06", "BTC/USD")
sData_df = Game.get_stock_prices("BTC/USD", f"2022-08-09 00:00", f"2022-08-10 01:00") 

Data_df = sData_df.iloc[::10, :].copy()
Data_df["close"] = sData_df["open"].iloc[9:-1:10].values
Data_df

ValueError: Length of values (150) does not match length of index (151)

In [26]:
import backend

Game = backend.GameManager("2022-06-06", "BTC/USD")
Data_df = Game.get_stock_prices("BTC/USD", f"2022-08-09 00:00", f"2022-08-10 01:00") 
lastpos = Data_df.loc[len(Data_df)-1, "close"]
sData_df = Data_df.iloc[1::2, :].reset_index(drop=True)
Data_df = Data_df.iloc[::2, :].reset_index(drop=True)
min_length = min(len(Data_df), len(sData_df))
Data_df = Data_df.iloc[:min_length, :]
sData_df = sData_df.iloc[:min_length, :]


Data_df["close"] = sData_df["close"]
Data_df

                          date          open  ...           low         close
0    2022-08-09 00:00:00+00:00  23830.109375  ...  23814.039062  23819.310547
1    2022-08-09 00:02:00+00:00  23808.730469  ...  23806.990234  23822.160156
2    2022-08-09 00:04:00+00:00  23829.990234  ...  23829.000000  23824.939453
3    2022-08-09 00:06:00+00:00  23823.019531  ...  23819.810547  23828.589844
4    2022-08-09 00:08:00+00:00  23830.150391  ...  23804.259766  23800.269531
..                         ...           ...  ...           ...           ...
745  2022-08-10 00:50:00+00:00  22731.750000  ...  22729.380859  22781.279297
746  2022-08-10 00:52:00+00:00  22784.800781  ...  22770.910156  22790.310547
747  2022-08-10 00:54:00+00:00  22789.050781  ...  22787.480469  22778.980469
748  2022-08-10 00:56:00+00:00  22778.310547  ...  22759.160156  22759.300781
749  2022-08-10 00:58:00+00:00  22777.220703  ...  22759.300781  22766.449219

[750 rows x 5 columns]